version: '3'

services:
  backend:
    image: pdfmerge-backend:1.0
    container_name: fastapi-container
    networks:
      - webnet
    restart: always
    environment:
      TZ: Asia/Tokyo
  frontend:
    image: pdfmerge-front:1.0
    container_name: vue-container
    ports:
      - 8080:8080
    networks:
      - webnet
    restart: always
    environment:
      TZ: Asia/Tokyo
networks:
  webnet: